
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.18.0
 * Query Engine version: 34b5a692b7bd79939a9a2c3ef97d816e749cda2f
 */
Prisma.prismaVersion = {
  client: "6.18.0",
  engine: "34b5a692b7bd79939a9a2c3ef97d816e749cda2f"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.TeamScalarFieldEnum = {
  id: 'id',
  name: 'name',
  key: 'key',
  groqApiKey: 'groqApiKey',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProjectScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  key: 'key',
  color: 'color',
  icon: 'icon',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  teamId: 'teamId',
  leadId: 'leadId',
  lead: 'lead',
  clientId: 'clientId'
};

exports.Prisma.WorkflowStateScalarFieldEnum = {
  id: 'id',
  name: 'name',
  type: 'type',
  color: 'color',
  position: 'position',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  teamId: 'teamId'
};

exports.Prisma.LabelScalarFieldEnum = {
  id: 'id',
  name: 'name',
  color: 'color',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  teamId: 'teamId'
};

exports.Prisma.IssueScalarFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  number: 'number',
  priority: 'priority',
  estimate: 'estimate',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  completedAt: 'completedAt',
  teamId: 'teamId',
  projectId: 'projectId',
  workflowStateId: 'workflowStateId',
  assigneeId: 'assigneeId',
  assignee: 'assignee',
  creatorId: 'creatorId',
  creator: 'creator'
};

exports.Prisma.IssueLabelScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  issueId: 'issueId',
  labelId: 'labelId'
};

exports.Prisma.CommentScalarFieldEnum = {
  id: 'id',
  content: 'content',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  issueId: 'issueId',
  userId: 'userId',
  user: 'user'
};

exports.Prisma.TeamMemberScalarFieldEnum = {
  id: 'id',
  role: 'role',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  teamId: 'teamId',
  userId: 'userId',
  userEmail: 'userEmail',
  userName: 'userName'
};

exports.Prisma.ProjectMemberScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  projectId: 'projectId',
  userId: 'userId',
  userEmail: 'userEmail',
  userName: 'userName'
};

exports.Prisma.InvitationScalarFieldEnum = {
  id: 'id',
  email: 'email',
  role: 'role',
  status: 'status',
  invitedBy: 'invitedBy',
  createdAt: 'createdAt',
  expiresAt: 'expiresAt',
  teamId: 'teamId'
};

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  emailVerified: 'emailVerified',
  image: 'image',
  username: 'username',
  dateOfBirth: 'dateOfBirth',
  joiningDate: 'joiningDate',
  position: 'position',
  department: 'department',
  employeeCode: 'employeeCode',
  phone: 'phone',
  location: 'location',
  bio: 'bio',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  twoFactorEnabled: 'twoFactorEnabled'
};

exports.Prisma.SessionScalarFieldEnum = {
  id: 'id',
  expiresAt: 'expiresAt',
  token: 'token',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  ipAddress: 'ipAddress',
  userAgent: 'userAgent',
  userId: 'userId'
};

exports.Prisma.AccountScalarFieldEnum = {
  id: 'id',
  accountId: 'accountId',
  providerId: 'providerId',
  userId: 'userId',
  accessToken: 'accessToken',
  refreshToken: 'refreshToken',
  idToken: 'idToken',
  accessTokenExpiresAt: 'accessTokenExpiresAt',
  refreshTokenExpiresAt: 'refreshTokenExpiresAt',
  scope: 'scope',
  password: 'password',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.VerificationScalarFieldEnum = {
  id: 'id',
  identifier: 'identifier',
  value: 'value',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TwoFactorScalarFieldEnum = {
  id: 'id',
  secret: 'secret',
  backupCodes: 'backupCodes',
  userId: 'userId'
};

exports.Prisma.RateLimitScalarFieldEnum = {
  id: 'id',
  key: 'key',
  count: 'count',
  lastRequest: 'lastRequest'
};

exports.Prisma.ChatConversationScalarFieldEnum = {
  id: 'id',
  teamId: 'teamId',
  userId: 'userId',
  title: 'title',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ChatMessageScalarFieldEnum = {
  id: 'id',
  conversationId: 'conversationId',
  role: 'role',
  content: 'content',
  toolCalls: 'toolCalls',
  createdAt: 'createdAt'
};

exports.Prisma.EventScalarFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  type: 'type',
  startTime: 'startTime',
  endTime: 'endTime',
  allDay: 'allDay',
  location: 'location',
  meetUrl: 'meetUrl',
  status: 'status',
  recurrence: 'recurrence',
  googleEventId: 'googleEventId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  teamId: 'teamId',
  projectId: 'projectId',
  creatorId: 'creatorId',
  creatorName: 'creatorName'
};

exports.Prisma.EventAttendeeScalarFieldEnum = {
  id: 'id',
  eventId: 'eventId',
  userId: 'userId',
  name: 'name',
  email: 'email',
  status: 'status',
  createdAt: 'createdAt'
};

exports.Prisma.MeetingNoteScalarFieldEnum = {
  id: 'id',
  eventId: 'eventId',
  content: 'content',
  summary: 'summary',
  decisions: 'decisions',
  rawTranscript: 'rawTranscript',
  followUpEmailDraft: 'followUpEmailDraft',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.MeetingActionItemScalarFieldEnum = {
  id: 'id',
  meetingNoteId: 'meetingNoteId',
  title: 'title',
  assigneeName: 'assigneeName',
  dueDate: 'dueDate',
  status: 'status',
  convertedIssueId: 'convertedIssueId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.StandupEntryScalarFieldEnum = {
  id: 'id',
  teamId: 'teamId',
  userId: 'userId',
  userName: 'userName',
  userEmail: 'userEmail',
  date: 'date',
  yesterday: 'yesterday',
  today: 'today',
  blockers: 'blockers',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ClientScalarFieldEnum = {
  id: 'id',
  name: 'name',
  company: 'company',
  industry: 'industry',
  website: 'website',
  email: 'email',
  phone: 'phone',
  address: 'address',
  city: 'city',
  state: 'state',
  country: 'country',
  gstin: 'gstin',
  status: 'status',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  teamId: 'teamId'
};

exports.Prisma.ContactScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  phone: 'phone',
  role: 'role',
  isPrimary: 'isPrimary',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  clientId: 'clientId'
};

exports.Prisma.LeadPipelineScalarFieldEnum = {
  id: 'id',
  name: 'name',
  isDefault: 'isDefault',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  teamId: 'teamId'
};

exports.Prisma.LeadStageScalarFieldEnum = {
  id: 'id',
  name: 'name',
  type: 'type',
  color: 'color',
  position: 'position',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  pipelineId: 'pipelineId'
};

exports.Prisma.LeadScalarFieldEnum = {
  id: 'id',
  title: 'title',
  companyName: 'companyName',
  contactName: 'contactName',
  email: 'email',
  phone: 'phone',
  industryVertical: 'industryVertical',
  source: 'source',
  campaign: 'campaign',
  estimatedValue: 'estimatedValue',
  currency: 'currency',
  expectedCloseDate: 'expectedCloseDate',
  requirementSummary: 'requirementSummary',
  temperature: 'temperature',
  ownerId: 'ownerId',
  ownerName: 'ownerName',
  nextFollowUpDate: 'nextFollowUpDate',
  isWon: 'isWon',
  isLost: 'isLost',
  lostReason: 'lostReason',
  lostNotes: 'lostNotes',
  convertedClientId: 'convertedClientId',
  convertedProjectId: 'convertedProjectId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  teamId: 'teamId',
  pipelineId: 'pipelineId',
  stageId: 'stageId',
  clientId: 'clientId'
};

exports.Prisma.LeadActivityScalarFieldEnum = {
  id: 'id',
  type: 'type',
  content: 'content',
  performedBy: 'performedBy',
  performedAt: 'performedAt',
  leadId: 'leadId'
};

exports.Prisma.TeamChannelScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  type: 'type',
  isPrivate: 'isPrivate',
  createdBy: 'createdBy',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  teamId: 'teamId',
  projectId: 'projectId'
};

exports.Prisma.TeamChannelMemberScalarFieldEnum = {
  id: 'id',
  channelId: 'channelId',
  userId: 'userId',
  userEmail: 'userEmail',
  userName: 'userName',
  lastReadAt: 'lastReadAt',
  createdAt: 'createdAt'
};

exports.Prisma.TeamChatMessageScalarFieldEnum = {
  id: 'id',
  channelId: 'channelId',
  senderId: 'senderId',
  senderName: 'senderName',
  senderEmail: 'senderEmail',
  senderAvatar: 'senderAvatar',
  content: 'content',
  attachments: 'attachments',
  mentions: 'mentions',
  referencedTaskId: 'referencedTaskId',
  isPinned: 'isPinned',
  isHuddle: 'isHuddle',
  huddleUrl: 'huddleUrl',
  parentId: 'parentId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TeamChatReactionScalarFieldEnum = {
  id: 'id',
  messageId: 'messageId',
  userId: 'userId',
  userName: 'userName',
  emoji: 'emoji',
  createdAt: 'createdAt'
};

exports.Prisma.TeamAnnouncementScalarFieldEnum = {
  id: 'id',
  teamId: 'teamId',
  title: 'title',
  content: 'content',
  priority: 'priority',
  authorId: 'authorId',
  authorName: 'authorName',
  isPinned: 'isPinned',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TeamAnnouncementAckScalarFieldEnum = {
  id: 'id',
  announcementId: 'announcementId',
  userId: 'userId',
  userName: 'userName',
  acknowledgedAt: 'acknowledgedAt'
};

exports.Prisma.InboxMessageScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  senderId: 'senderId',
  senderName: 'senderName',
  senderEmail: 'senderEmail',
  senderAvatar: 'senderAvatar',
  subject: 'subject',
  snippet: 'snippet',
  content: 'content',
  category: 'category',
  entityType: 'entityType',
  entityId: 'entityId',
  entityUrl: 'entityUrl',
  read: 'read',
  starred: 'starred',
  archived: 'archived',
  teamId: 'teamId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AuditLogScalarFieldEnum = {
  id: 'id',
  teamId: 'teamId',
  userId: 'userId',
  userName: 'userName',
  userEmail: 'userEmail',
  action: 'action',
  entityType: 'entityType',
  entityId: 'entityId',
  entityTitle: 'entityTitle',
  details: 'details',
  ipAddress: 'ipAddress',
  createdAt: 'createdAt'
};

exports.Prisma.CompanySettingScalarFieldEnum = {
  id: 'id',
  teamId: 'teamId',
  companyName: 'companyName',
  legalEntityName: 'legalEntityName',
  gstin: 'gstin',
  pan: 'pan',
  currency: 'currency',
  timezone: 'timezone',
  fiscalYearStart: 'fiscalYearStart',
  workingDays: 'workingDays',
  businessHours: 'businessHours',
  holidays: 'holidays',
  address: 'address',
  city: 'city',
  state: 'state',
  pincode: 'pincode',
  billingEmail: 'billingEmail',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AutomationRuleScalarFieldEnum = {
  id: 'id',
  teamId: 'teamId',
  name: 'name',
  description: 'description',
  triggerType: 'triggerType',
  triggerConfig: 'triggerConfig',
  actionType: 'actionType',
  actionConfig: 'actionConfig',
  isActive: 'isActive',
  executionCount: 'executionCount',
  lastTriggeredAt: 'lastTriggeredAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AutomationLogScalarFieldEnum = {
  id: 'id',
  ruleId: 'ruleId',
  status: 'status',
  details: 'details',
  executedAt: 'executedAt'
};

exports.Prisma.DeveloperApiKeyScalarFieldEnum = {
  id: 'id',
  teamId: 'teamId',
  name: 'name',
  keyPrefix: 'keyPrefix',
  keyHash: 'keyHash',
  scopes: 'scopes',
  createdBy: 'createdBy',
  createdByName: 'createdByName',
  lastUsedAt: 'lastUsedAt',
  expiresAt: 'expiresAt',
  isActive: 'isActive',
  createdAt: 'createdAt'
};

exports.Prisma.WebhookEndpointScalarFieldEnum = {
  id: 'id',
  teamId: 'teamId',
  url: 'url',
  description: 'description',
  secret: 'secret',
  events: 'events',
  isActive: 'isActive',
  lastStatus: 'lastStatus',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.WebhookDeliveryScalarFieldEnum = {
  id: 'id',
  endpointId: 'endpointId',
  event: 'event',
  statusCode: 'statusCode',
  payload: 'payload',
  response: 'response',
  deliveredAt: 'deliveredAt'
};

exports.Prisma.CompanyKpiScalarFieldEnum = {
  id: 'id',
  teamId: 'teamId',
  category: 'category',
  name: 'name',
  metricKey: 'metricKey',
  targetValue: 'targetValue',
  currentValue: 'currentValue',
  unit: 'unit',
  period: 'period',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.InvoiceScalarFieldEnum = {
  id: 'id',
  teamId: 'teamId',
  clientId: 'clientId',
  projectId: 'projectId',
  invoiceNumber: 'invoiceNumber',
  status: 'status',
  issueDate: 'issueDate',
  dueDate: 'dueDate',
  paidAt: 'paidAt',
  currency: 'currency',
  subtotal: 'subtotal',
  discount: 'discount',
  taxTotal: 'taxTotal',
  grandTotal: 'grandTotal',
  amountPaid: 'amountPaid',
  balanceDue: 'balanceDue',
  supplyType: 'supplyType',
  cgstAmount: 'cgstAmount',
  sgstAmount: 'sgstAmount',
  igstAmount: 'igstAmount',
  notes: 'notes',
  paymentTerms: 'paymentTerms',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.InvoiceItemScalarFieldEnum = {
  id: 'id',
  invoiceId: 'invoiceId',
  description: 'description',
  hsnSac: 'hsnSac',
  quantity: 'quantity',
  unitPrice: 'unitPrice',
  taxRate: 'taxRate',
  amount: 'amount',
  createdAt: 'createdAt'
};

exports.Prisma.PaymentScalarFieldEnum = {
  id: 'id',
  teamId: 'teamId',
  invoiceId: 'invoiceId',
  amount: 'amount',
  currency: 'currency',
  paymentDate: 'paymentDate',
  paymentMethod: 'paymentMethod',
  referenceNumber: 'referenceNumber',
  receiptNumber: 'receiptNumber',
  notes: 'notes',
  createdAt: 'createdAt'
};

exports.Prisma.ExpenseScalarFieldEnum = {
  id: 'id',
  teamId: 'teamId',
  projectId: 'projectId',
  vendorName: 'vendorName',
  category: 'category',
  amount: 'amount',
  currency: 'currency',
  expenseDate: 'expenseDate',
  paymentStatus: 'paymentStatus',
  isBillable: 'isBillable',
  receiptNote: 'receiptNote',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ToolSubscriptionScalarFieldEnum = {
  id: 'id',
  teamId: 'teamId',
  name: 'name',
  category: 'category',
  cost: 'cost',
  currency: 'currency',
  billingCycle: 'billingCycle',
  renewalDate: 'renewalDate',
  ownerName: 'ownerName',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.DomainProductScalarFieldEnum = {
  id: 'id',
  teamId: 'teamId',
  name: 'name',
  slug: 'slug',
  tagline: 'tagline',
  description: 'description',
  vertical: 'vertical',
  status: 'status',
  ownerName: 'ownerName',
  pricingModel: 'pricingModel',
  targetQuarter: 'targetQuarter',
  websiteUrl: 'websiteUrl',
  repositoryUrl: 'repositoryUrl',
  mrr: 'mrr',
  activeUsers: 'activeUsers',
  healthScore: 'healthScore',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProductRoadmapItemScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  teamId: 'teamId',
  title: 'title',
  description: 'description',
  quarter: 'quarter',
  stage: 'stage',
  priority: 'priority',
  progress: 'progress',
  targetDate: 'targetDate',
  effortEstimate: 'effortEstimate',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProductFeatureRequestScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  teamId: 'teamId',
  title: 'title',
  description: 'description',
  category: 'category',
  source: 'source',
  requesterName: 'requesterName',
  voteCount: 'voteCount',
  status: 'status',
  upvotedBy: 'upvotedBy',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProductPilotCustomerScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  teamId: 'teamId',
  clientId: 'clientId',
  companyName: 'companyName',
  contactName: 'contactName',
  contactEmail: 'contactEmail',
  stage: 'stage',
  startDate: 'startDate',
  endDate: 'endDate',
  feedbackNotes: 'feedbackNotes',
  healthScore: 'healthScore',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProductReleaseNoteScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  teamId: 'teamId',
  version: 'version',
  title: 'title',
  releaseDate: 'releaseDate',
  isPublished: 'isPublished',
  features: 'features',
  improvements: 'improvements',
  fixes: 'fixes',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ReusableComponentScalarFieldEnum = {
  id: 'id',
  teamId: 'teamId',
  name: 'name',
  category: 'category',
  description: 'description',
  techStack: 'techStack',
  repoUrl: 'repoUrl',
  timesReused: 'timesReused',
  hoursSavedEstimate: 'hoursSavedEstimate',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};


exports.Prisma.ModelName = {
  Team: 'Team',
  Project: 'Project',
  WorkflowState: 'WorkflowState',
  Label: 'Label',
  Issue: 'Issue',
  IssueLabel: 'IssueLabel',
  Comment: 'Comment',
  TeamMember: 'TeamMember',
  ProjectMember: 'ProjectMember',
  Invitation: 'Invitation',
  User: 'User',
  Session: 'Session',
  Account: 'Account',
  Verification: 'Verification',
  TwoFactor: 'TwoFactor',
  RateLimit: 'RateLimit',
  ChatConversation: 'ChatConversation',
  ChatMessage: 'ChatMessage',
  Event: 'Event',
  EventAttendee: 'EventAttendee',
  MeetingNote: 'MeetingNote',
  MeetingActionItem: 'MeetingActionItem',
  StandupEntry: 'StandupEntry',
  Client: 'Client',
  Contact: 'Contact',
  LeadPipeline: 'LeadPipeline',
  LeadStage: 'LeadStage',
  Lead: 'Lead',
  LeadActivity: 'LeadActivity',
  TeamChannel: 'TeamChannel',
  TeamChannelMember: 'TeamChannelMember',
  TeamChatMessage: 'TeamChatMessage',
  TeamChatReaction: 'TeamChatReaction',
  TeamAnnouncement: 'TeamAnnouncement',
  TeamAnnouncementAck: 'TeamAnnouncementAck',
  InboxMessage: 'InboxMessage',
  AuditLog: 'AuditLog',
  CompanySetting: 'CompanySetting',
  AutomationRule: 'AutomationRule',
  AutomationLog: 'AutomationLog',
  DeveloperApiKey: 'DeveloperApiKey',
  WebhookEndpoint: 'WebhookEndpoint',
  WebhookDelivery: 'WebhookDelivery',
  CompanyKpi: 'CompanyKpi',
  Invoice: 'Invoice',
  InvoiceItem: 'InvoiceItem',
  Payment: 'Payment',
  Expense: 'Expense',
  ToolSubscription: 'ToolSubscription',
  DomainProduct: 'DomainProduct',
  ProductRoadmapItem: 'ProductRoadmapItem',
  ProductFeatureRequest: 'ProductFeatureRequest',
  ProductPilotCustomer: 'ProductPilotCustomer',
  ProductReleaseNote: 'ProductReleaseNote',
  ReusableComponent: 'ReusableComponent'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
